In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [2]:
automobiles_data = pd.read_csv('datasets/CarPrice_Assignment.csv')

automobiles_data.head()

car_ID  symboling                   CarName fueltype aspiration doornumber  \
0       1          3        alfa-romero giulia      gas        std        two   
1       2          3       alfa-romero stelvio      gas        std        two   
2       3          1  alfa-romero Quadrifoglio      gas        std        two   
3       4          2               audi 100 ls      gas        std       four   
4       5          2                audi 100ls      gas        std       four   

       carbody drivewheel enginelocation  wheelbase  ...  enginesize  \
0  convertible        rwd          front       88.6  ...         130   
1  convertible        rwd          front       88.6  ...         130   
2    hatchback        rwd          front       94.5  ...         152   
3        sedan        fwd          front       99.8  ...         109   
4        sedan        4wd          front       99.4  ...         136   

   fuelsystem  boreratio  stroke compressionratio horsepower  peakrpm citympg  \
0        mpfi       3.47    2.68              9.0        111     5000      21   
1        mpfi       3.47    2.68              9.0        111     5000      21   
2        mpfi       2.68    3.47              9.0        154     5000      19   
3        mpfi       3.19    3.40             10.0        102     5500      24   
4        mpfi       3.19    3.40              8.0        115     5500      18   

   highwaympg    price  
0          27  13495.0  
1          27  16500.0  
2          26  16500.0  
3          30  13950.0  
4          22  17450.0  

[5 rows x 26 columns]

In [3]:
automobiles_data.columns

Index(['car_ID', 'symboling', 'CarName', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg',
       'price'],
      dtype='object')

In [4]:
automobiles_data.drop(['car_ID', 'symboling', 'CarName'], axis=1, inplace=True)

In [5]:
automobiles_data = pd.get_dummies(automobiles_data, drop_first = True)

In [6]:
automobiles_data.shape

(205, 43)

In [7]:
X = automobiles_data.drop('price', axis=1)

Y = automobiles_data['price']

In [8]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

In [9]:
x_train.shape, x_test.shape

((164, 42), (41, 42))

In [10]:
y_train.shape, y_test.shape

((164,), (41,))

In [11]:
model = LinearRegression().fit(x_train, y_train)

In [12]:
Training_score = model.score(x_train, y_train)

Training_score

0.9497946603428231

In [13]:
y_pred = model.predict(x_test)

y_pred

array([ 6359.54691607,  9288.94139795, 10000.04974406,  7448.10779814,
       13196.18906812,  8277.13032793, 11031.97691935,  6318.7154884 ,
       29968.53911379,  7670.60390765,  7101.39053972,  7044.02864417,
        5954.89186716,  7414.43353061,  8668.45906296,  9338.26178002,
       21293.617684  , 14500.29945711,  6418.30540669,  5536.18941763,
       11423.53323761,  6100.03649089, 19564.76869129,  6362.29622564,
        5500.45450961, 12598.81772818, 47446.704644  , 12351.32344888,
        6322.2434349 , 12286.04004258,  6477.81835401, 19821.26519128,
        7157.17920868, 10760.53349575, 16994.24287706,  9725.21595674,
       20185.101662  , 16978.56831299,  7906.15490959, 11709.60798392,
       11906.72704715])

In [14]:
Testing_score = r2_score(y_test, y_pred)

Testing_score

0.8008689410969345

In [15]:
import json

In [16]:
model.coef_

array([ 8.69423010e+01, -7.75884997e+01,  5.88499838e+02,  2.64328938e+01,
        3.58398297e+00,  1.08529611e+02, -1.26493442e+03, -4.52141451e+03,
       -4.97601296e+02,  1.88797000e+01,  1.84851330e+00, -1.44874739e+02,
        1.48201952e+02, -3.76371633e+03,  2.17843935e+03, -8.38952598e+01,
       -3.20645011e+03, -3.39990577e+03, -2.39288109e+03, -3.24907890e+03,
        1.38407990e+02,  5.99635094e+02,  8.69893555e+03, -8.45413709e+03,
       -1.75385286e+03,  2.36812806e+03, -1.80691964e+02, -5.27099024e+03,
       -7.45581954e+02, -8.50707210e+03, -1.02419458e+04, -7.23826472e+03,
       -8.72217306e+02,  1.81898940e-12, -7.45581954e+02, -3.00817307e+02,
       -1.51915246e+03,  3.76371633e+03, -3.92629181e+03, -4.62351106e+02,
       -3.06981326e+03, -4.01050553e+02])

In [17]:
model.intercept_

-19668.185034957274

In [18]:
model_param = {}

model_param['coef'] = list(model.coef_)
model_param['intercept'] = model.intercept_.tolist()

In [19]:
json_txt = json.dumps(model_param, indent=4)

json_txt

'{\n    "coef": [\n        86.94230097660915,\n        -77.58849969114668,\n        588.4998380777262,\n        26.432893802654135,\n        3.5839829679142805,\n        108.5296105143836,\n        -1264.9344218988372,\n        -4521.414512549939,\n        -497.60129613501783,\n        18.879699954734935,\n        1.848513301419362,\n        -144.87473882797957,\n        148.20195177517041,\n        -3763.7163278065564,\n        2178.4393530504512,\n        -83.89525975052591,\n        -3206.450114890701,\n        -3399.905773970466,\n        -2392.8810906324848,\n        -3249.078897081869,\n        138.40798985468194,\n        599.6350940643096,\n        8698.935548013751,\n        -8454.137088382751,\n        -1753.8528640433608,\n        2368.1280555595517,\n        -180.69196440689936,\n        -5270.990239554368,\n        -745.5819535104251,\n        -8507.072098068797,\n        -10241.945822816355,\n        -7238.264722568536,\n        -872.21730634124,\n        1.81898940354585

In [20]:
with open('models/regressor_param.txt', 'w') as file:
    
    file.write(json_txt)

In [21]:
with open('models/regressor_param.txt', 'r') as file:
    
    json_text=json.load(file)

In [22]:
json_model = LinearRegression()

In [23]:
json_model.coef_ = np.array(json_text['coef'])
json_model.intercept_ = np.array(json_text['intercept'])

In [24]:
y_pred = json_model.predict(x_test)

r2_score(y_test, y_pred)

0.8008689410969345

In [25]:
Testing_score

0.8008689410969345

In [26]:
import pickle

In [27]:
pickle.dump(model, open('models/model.pkl', 'wb'))

In [28]:
pickle_model = pickle.load(open('models/model.pkl', 'rb'))

In [29]:
y_pred = pickle_model.predict(x_test)

y_pred

array([ 6359.54691607,  9288.94139795, 10000.04974406,  7448.10779814,
       13196.18906812,  8277.13032793, 11031.97691935,  6318.7154884 ,
       29968.53911379,  7670.60390765,  7101.39053972,  7044.02864417,
        5954.89186716,  7414.43353061,  8668.45906296,  9338.26178002,
       21293.617684  , 14500.29945711,  6418.30540669,  5536.18941763,
       11423.53323761,  6100.03649089, 19564.76869129,  6362.29622564,
        5500.45450961, 12598.81772818, 47446.704644  , 12351.32344888,
        6322.2434349 , 12286.04004258,  6477.81835401, 19821.26519128,
        7157.17920868, 10760.53349575, 16994.24287706,  9725.21595674,
       20185.101662  , 16978.56831299,  7906.15490959, 11709.60798392,
       11906.72704715])

In [30]:
r2_score(y_test, y_pred)

0.8008689410969345

In [31]:
Testing_score

0.8008689410969345

In [32]:
import joblib

In [33]:
filename = 'models/model.joblib'

In [34]:
joblib.dump(model, filename)

['models/model.joblib']

In [35]:
joblib_model = joblib.load(filename)

In [36]:
y_pred = joblib_model.predict(x_test)

y_pred

array([ 6359.54691607,  9288.94139795, 10000.04974406,  7448.10779814,
       13196.18906812,  8277.13032793, 11031.97691935,  6318.7154884 ,
       29968.53911379,  7670.60390765,  7101.39053972,  7044.02864417,
        5954.89186716,  7414.43353061,  8668.45906296,  9338.26178002,
       21293.617684  , 14500.29945711,  6418.30540669,  5536.18941763,
       11423.53323761,  6100.03649089, 19564.76869129,  6362.29622564,
        5500.45450961, 12598.81772818, 47446.704644  , 12351.32344888,
        6322.2434349 , 12286.04004258,  6477.81835401, 19821.26519128,
        7157.17920868, 10760.53349575, 16994.24287706,  9725.21595674,
       20185.101662  , 16978.56831299,  7906.15490959, 11709.60798392,
       11906.72704715])

In [37]:
r2_score(y_test, y_pred)

0.8008689410969345

In [38]:
Testing_score

0.8008689410969345